### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sdid' of undefined -- biojournal--14037316.min.gz.js:1665

### ISSUE THREAD

**Issue by AgataJot** [samsungsamiio/samsungsami.io#3]
Error is being thrown on line at: ```biojournal--14037316.min.gz.js:1665``` when loading the [charts dashboard](https://portal.samsungsami.io/#/data)

```Uncaught TypeError: Cannot read property 'sdid' of undefined```
This happens if the data object is empty, ```data = {}```

On a separate note, I followed the [smoke detector tutorial](http://www.instructables.com/id/Make-a-fire-detector-in-minutes-with-Samsung-SAMII/?ALLSTEPS) (though admittedly not to the letter), and can't seem to get the data I'm sending to register. Here's the console output, and imo it looks correct:
```
isWebSocketReady true

Sending payload {"sdid":"41d004c0faf24a26b0cd6d9ab2ba4cae", "ts": 1444561838747, "data": {"onFire":true}, "cid":"1444561838747"}

Received message: {"data":{"mid":"a5deef6e8572405f85f084464f03f0c8","cid":"1444561838747"}}
```

However, when inspecting the messages sent from the [dashboard](https://portal.samsungsami.io/#/messages), data objects are displayed as empty.

**Comment by yujingwu** [comment]
Agata,

You closed this issue. 

It seems that "Uncaught TypeError: Cannot read property 'sdid' of undefined" is gone??

How about your separate note? Did you see your messages on the User Portal (portal.samsungsami.io)? If not, please make you comment on  http://www.instructables.com/id/Make-a-fire-detector-in-minutes-with-Samsung-SAMII/ . Then I will take a look. Please give more detailed information when you comment.
