### ISSUE TITLE
Eclipse support for Android is coming to END

### ISSUE THREAD

**Issue by ramichetty99** [samsungsamiio/samsungsami.io#5]
As the Google Made and official announcement that the Support for the Android Plugin for eclipse is coming to and END , going forward it will be Android Studio that will be used for the Android Development but in the below link it is given as integration of the Java/ Android with maven as the Build and Eclipse as the IDE, if this is the case Android Studio uses Gradle for Build and java Build from Eclipse , .APK from Android Studio has to work in coordination. is the support for the Development using the Android Plugin for will still be there or it will be Android studio as per the IDE usage standards defined by the Google.

**Comment by yujingwu** [comment]
Which link are you referring to when you say "in the below link"?
https://developer.samsungsami.io/sami/demos-tools/your-first-android-app.html

If so, we already have an internal ticket for it, yet need to work on it. You remind me to convert that ticket to github ticket so everyone can see it.

All sample apps below are using Android Studio
 https://developer.samsungsami.io/sami/samples/

**Comment by yujingwu** [comment]
"Your first Android application" is updated with instructions and zip file for Android Studio
https://developer.samsungsami.io/sami/demos-tools/your-first-android-app.html 

"Java/Android SDK" is enhanced with the instruction about how to modify build.gradle file.
https://developer.samsungsami.io/sami/native-SDKs/android-SDK.html
https://developer.samsungsami.io/sami/native-SDKs/android-SDK.html
