### ISSUE TITLE
Smartthings Hub with SAMIIO

### ISSUE THREAD

**Issue by manikantesh** [samsungsamiio/samsungsami.io#6]
Hi I have a problem of connecting Smartthings hub connected devices to integrate with SAMIIO. I used devices already available there in the list but I am getting unwanted results not from my sensor. Can anyone please help me to add my devices to SAMIIO

**Comment by yujingwu** [comment]
In smartthings app, under smart apps tab you should be able to find SAMI. Install it to give a try. 
You also need to register a account on portal.samsungsami.io or devportal.samsungsami.io

**Comment by yujingwu** [comment]
I have not received the details of the issue. Close this one.

**Comment by manikantesh** [comment]
Hi I have another problem so that is the reason I didn't close the issue. Who Can I get sensor values from SAMIIO in the form of http requests.
