### ISSUE TITLE
VR9000

### ISSUE THREAD

**Issue by aquaria1984** [samsungsamiio/samsungsami.io#7]
Hi,

on the blog dated 11-3-15 it showed the vr9000 (robot vacuum) being controlled with the smartthings application. When will this device type be released as I have asked Smartthings and they are unable to provide a timeline.

**Comment by yujingwu** [comment]
Connecting the robot vaccum to SAMI is an internal experiment that illustrate the SAMI's capability as data exchanger and device agnostics. However, at this point, we don’t have a plan to release it to the public. To receive SAMI integration news, please join our mailing list at https://blog.samsungsami.io/

Thank you for your interest.

**Comment by aquaria1984** [comment]
Alright well back to the store it goes then as i bought it to integrate with smartthings.


Sent from Yahoo Mail on Android 
 
  On Mon, Nov 30, 2015 at 3:48 PM, Yujing Wu<notifications@github.com> wrote:   
Connecting the robot vaccum to SAMI is an internal experiment that illustrate the SAMI's capability as data exchanger and device agnostics. However, at this point, we don’t have a plan to release it to the public. To receive SAMI integration news, please join our mailing list at https://blog.samsungsami.io/

Thank you for your interest.
