### ISSUE TITLE
Hi I have a problem regarding SAMIIO. How can I get sensors data from SAMIIO through http request?

### ISSUE THREAD

**Issue by manikantesh** [samsungsamiio/samsungsami.io#8]
I have tried to get this but I am facing authentication problem while trying.

**Comment by yujingwu** [comment]
I need more details in order to understand your question and issue.

Which sensor? What is the type? Who owns it? Does the sensor have anything to do with smartthings?

If you are build an app to access the sensor data owned by user, your app needs to design login screen  for user to log in then the app get a user token. You must obtain a valid token in order to access device data https://developer.samsungsami.io/sami/demos-tools/your-first-android-app.html#demo

If you own the sensor and you can connect it to SAMI, your app can use device token to read data
https://developer.samsungsami.io/sami/demos-tools/your-first-iot-device.html#step-1-create-and-connect-a-new-device-type

**Comment by manikantesh** [comment]
Hi Wu,

I am using Aeno multi sensor connected to Smartthings hub. I added this
device to SAMIIO to get the data into my local machine in the form of Json.
But I want to have this information through https request. Can I request
sensor data through http whenever I want with you using any application?

If possible can you please specify me how to do it

Thanks and Regards,

*Manikantesh Kilaru,*

*Graduate Assistant, Marketing and Communications Technology*
Ball State University Foundation

2800 W. Bethel Ave

Muncie, Indiana 47304

P: 201-565-6661

Toll Free: 1-888-I-GO-4-BSU
*kmanikantesh*@bsu.edu <cmorris@bsu.edu>

bsu.edu/give <http://www.bsu.edu/give>

@BSUFoundation <http://www.twitter.com/BSUFoundation>

**Comment by yujingwu** [comment]
Yes, you can make API call to get the data of your smart devices that has been connected to SAMI. 

I do not have Aeno sensor, but I can use SmartThings Outlet as an example.

  1. Import outlet to SAMI using SAMI  SmartApps within SmartThings mobile app
  2. I can see this device "SmartThings Outlet 1" in my SAMI user portal per screenshot below ![devicelist](https://cloud.githubusercontent.com/assets/9285724/12026579/237ba4ee-ad70-11e5-8657-55f3c081b8c7.png)

  3. I can also see the data of this device in SAMI user portal per screenshot 
![outletdata_samiportal](https://cloud.githubusercontent.com/assets/9285724/12026587/41953c4c-ad70-11e5-87a6-61d76f0e1fb8.png)

  4. Get the device ID and device token of my outlet 1 by following 
https://developer.samsungsami.io/sami/sami-documentation/developer-user-portals.html#managing-a-device-token
  5.  File an API call to get the data from this device. Below is an example that uses curl command
You should replace MY_ACCESS_TOKEN and MY_DEVICE_ID by device token and device ID obtained in the above step
~~~
$ curl -H "Authorization:bearer MY_ACCESS_TOKEN" "https://api.samsungsami.io/v1.1/messages/last?count=2&sdids=MY_DEVICE_ID"
~~~
Here is results of the above command

~~~
{"sdids":"c7554de7f61f4769b31074c7c178fc75","count":2,"size":2,"data":[{"mid":"40bd6e63e11941da98555f48741fb87e","data":{"power":0.6},"ts":1450460041826,"sdtid":"dtae1fe59cebe041f5aeb11ff777988c78","cts":1450460041825,"uid":"240bc34cf61348e6a3255fe5d8539484","mv":1,"sdid":"c7554de7f61f4769b31074c7c178fc75"},{"mid":"439adee27a7e456a8a5b921a204242d3","data":{"switch":"on"},"ts":1450460041239,"sdtid":"dtae1fe59cebe041f5aeb11ff777988c78","cts":1450460041239,"uid":"240bc34cf61348e6a3255fe5d8539484","mv":1,"sdid":"c7554de7f61f4769b31074c7c178fc75"}]}
~~~

The data are consistent with ones shown in the User Portal in Step 3.

=======
More information:

  1. [The REST API documentation for getting messages](https://developer.samsungsami.io/sami/api-spec.html#get-last-normalized-messages)
  2. For step 4 above, I used a device token, which is one type of three access token types. Consult [Authentication document](https://developer.samsungsami.io/sami/sami-documentation/authentication.html) to learn how to get other access token.
  3. You can try [API Console](https://developer.samsungsami.io/sami/demos-tools/api-console.html) to make HTTP request call without writing a single line of code. In this case, you replace Step 4 and 5 using API Console.
